### ISSUE TITLE
Include a mention of other Swift 6 source breaking changes

### ISSUE THREAD

**Issue by dempseyatgithub** [apple/swift-migration-guide#44]
Although the largest compatibility issue in moving to Swift 6 is certainly strict concurrency checking, some developers will encounter a variety of the other (hopefully rare) source breakages introduced in Swift 6.

The migration guide should mention these somewhere, since they are a part and potential stumbling bloc to migration to Swift 6 language mode.

**Comment by mattmassicotte** [comment]
hmmmmm, yes. I'll have to track down which proposals could introduce source breaking changes.

@hborla do you happen know?

**Comment by hborla** [comment]
Yep!

SE-0192: `NonfrozenEnumExhaustivity`
SE-0274: `ConciseMagicFile`
SE-0286 : `ForwardTrailingClosures`
SE-0337:  `StrictConcurrency`
SE-0352: `ImplicitOpenExistentials`
SE-0354: `BareSlashRegexLiterals`
SE-0383: `DeprecateApplicationMain`
SE-0384: `ImportObjcForwardDeclarations`
SE-0401: `DisableOutwardActorInference`
SE-0411: `IsolatedDefaultValues`
SE-0412: `GlobalConcurrency`
SE-0414: `RegionBasedIsolation`
SE-0418: `InferSendableFromCaptures`
SE-0423: `DynamicActorIsolation`
SE-0434: `GlobalActorIsolatedTypesUsability`

**Comment by mattmassicotte** [comment]
Ok, thank you!

I just looked through a bunch of proposals myself, and there were also source compatibility issues brought up in these:

https://github.com/apple/swift-evolution/blob/main/proposals/0413-typed-throws.md
https://github.com/apple/swift-evolution/blob/main/proposals/0431-isolated-any-functions.md
https://github.com/apple/swift-evolution/blob/main/proposals/0432-noncopyable-switch.md
https://github.com/apple/swift-evolution/blob/main/proposals/0436-objc-implementation.md
https://github.com/apple/swift-evolution/blob/main/proposals/0437-noncopyable-stdlib-primitives.md#source-compatibility
https://github.com/apple/swift-evolution/blob/main/proposals/0438-metatype-keypath.md

I guess if not gated by an upcoming feature flag they aren't enough of a concern?

**Comment by hborla** [comment]
>https://github.com/apple/swift-evolution/blob/main/proposals/0413-typed-throws.md

`FullTypedThrows` will be an upcoming feature, but the implementation isn't complete and it is not an upcoming feature for Swift 6.

>https://github.com/apple/swift-evolution/blob/main/proposals/0431-isolated-any-functions.md

The source compatibility issues mentioned here are outlined for completeness, but you can only really encounter them if you're referencing one of the concurrency library APIs unapplied, like `let fn = Task.init`, which we doubt anybody is actually doing in practice. Source compatibility issues caused by standard library changes also can't be staged in using upcoming features - upcoming features only control compiler behaviors. I don't think this potential source compatibility issue is worth mentioning in this guide.

>https://github.com/apple/swift-evolution/blob/main/proposals/0432-noncopyable-switch.md

It seems this section of the proposal is out of date, thanks for pointing this out! We'll fix this in the proposal.

>https://github.com/apple/swift-evolution/blob/main/proposals/0436-objc-implementation.md

My read of this section is that it does not have any source compatibility impact. Source Compatibility is just a standard section of evolution proposals that should always be filled out, even if it says there is no source compatibility impact.

>https://github.com/apple/swift-evolution/blob/main/proposals/0437-noncopyable-stdlib-primitives.md#source-compatibility

This is a standard library change that can't be gated by upcoming features.

>https://github.com/apple/swift-evolution/blob/main/proposals/0438-metatype-keypath.md

This feature is not for Swift 6.

**Comment by mattmassicotte** [comment]
Ok, so great, so those are nothing to worry about. Thank you!

**Comment by vanvoorden** [comment]
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md#default-import-access-level-in-swift-5-and-swift-6

> In Swift 6 mode, an import is `internal` by default. This will align the behavior of imports with declarations where the implicit access level is internal. It should help limit unintentional dependency creep as marking a dependency public will require an explicit modifier. […] The Swift 6 change will likely break source compatibility for libraries.

What about SE-0409?

**Comment by mattmassicotte** [comment]
I made an attempt at this here: https://github.com/apple/swift-migration-guide/pull/106
