### ISSUE TITLE
Package does not compile under currently released version of Swift (5.10 at time of filing issue)

### ISSUE THREAD

**Issue by Diggory** [apple/swift-migration-guide#90]
Hello, 

Currently the package does not compile using currently released (June 2024 at time of filing issue)  versions of Swift. (macOS Sonoma 14.5, Swift 5.10.0). 

The Package Manifest uses tools v6
`package 'swift-migration-guide' is using Swift tools version 6.0.0 but the installed version is 5.10.0`

And the target `Swift5Examples` uses a `.swiftSetting` (`.swiftLanguageVersion(.v5)`) that's only available in tools v6.

```
Type 'Array<SwiftSetting>.ArrayLiteralElement' (aka 'SwiftSetting') has no member 'swiftLanguageVersion'

Cannot infer contextual base in reference to member 'v5'
```

Is this package only intended to be used with Swift v6 or should there be a  `Package@swift-5.6.swift` version of the manifest?

**Comment by mattmassicotte** [comment]
I went back and forth about this one. Ultimately, we opted to require a Swift 6 compiler.

Maintaining Swift 5.10 compatibility required a lot of conditional compilation. And, since they are so many critical concurrency-related features that are only available with the latest compiler even in Swift 5 mode, it seemed like the best choice.
